jobs:
  main:
    if: ${{ github.repository == 'spring-projects/spring-security' }}
    permissions:
      contents: none
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GH_ACTIONS_REPO_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      name: Delete artifacts in cron job
      run: 'echo "Running clean build artifacts logic"

        output=$(curl -X GET -H "Authorization: token $GH_ACTIONS_REPO_TOKEN" https://api.github.com/repos/spring-projects/spring-security/actions/artifacts
        | grep ''"id"'' | cut -d : -f2 | sed ''s/,*$//g'')

        echo Output is $output

        for id in $output; do curl -X DELETE -H "Authorization: token $GH_ACTIONS_REPO_TOKEN"
        https://api.github.com/repos/spring-projects/spring-security/actions/artifacts/$id;
        done;

        '
name: Clean build artifacts
on:
  repository_dispatch:
    types: trigger-ga___clean_build_artifacts.yml
permissions:
  contents: read
