env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
jobs:
  build:
    name: Build
    secrets: inherit
    strategy:
      matrix:
        jdk:
        - 17
        os:
        - ubuntu-latest
        - windows-latest
    uses: spring-io/spring-security-release-tools/.github/workflows/build.yml@v1
    with:
      distribution: temurin
      java-version: ${{ matrix.jdk }}
      runs-on: ${{ matrix.os }}
  check-tangles:
    if: ${{ github.repository_owner == 'spring-projects' }}
    name: Check for Package Tangles
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up gradle
      uses: spring-io/spring-gradle-build-action@v2
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        STRUCTURE101_LICENSEID: ${{ secrets.STRUCTURE101_LICENSEID }}
      name: Check for package tangles
      run: './gradlew check s101 -Ps101.licenseId="$STRUCTURE101_LICENSEID" --stacktrace

        '
  deploy-artifacts:
    name: Deploy Artifacts
    needs:
    - build
    - test
    - check-tangles
    secrets: inherit
    uses: spring-io/spring-security-release-tools/.github/workflows/deploy-artifacts.yml@v1
    with:
      should-deploy-artifacts: ${{ needs.build.outputs.should-deploy-artifacts }}
  deploy-docs:
    name: Deploy Docs
    needs:
    - build
    - test
    - check-tangles
    secrets: inherit
    uses: spring-io/spring-security-release-tools/.github/workflows/deploy-docs.yml@v1
    with:
      should-deploy-docs: ${{ needs.build.outputs.should-deploy-artifacts }}
  deploy-schema:
    name: Deploy Schema
    needs:
    - build
    - test
    - check-tangles
    secrets: inherit
    uses: spring-io/spring-security-release-tools/.github/workflows/deploy-schema.yml@v1
    with:
      should-deploy-schema: ${{ needs.build.outputs.should-deploy-artifacts }}
  notify_result:
    if: failure()
    name: Check for failures
    needs:
    - perform-release
    permissions:
      actions: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Send Slack message
      uses: sjohnr/slack-workflow-status@v1-beta
      with:
        channel: '#spring-security-ci'
        name: CI Notifier
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  perform-release:
    name: Perform Release
    needs:
    - deploy-artifacts
    - deploy-docs
    - deploy-schema
    secrets: inherit
    uses: spring-io/spring-security-release-tools/.github/workflows/perform-release.yml@v1
    with:
      artifact-path: org/springframework/security/spring-security-core
      milestone-repo-url: https://repo.spring.io/artifactory/milestone
      project-version: ${{ needs.deploy-artifacts.outputs.project-version }}
      release-repo-url: https://repo1.maven.org/maven2
      should-perform-release: ${{ needs.deploy-artifacts.outputs.artifacts-deployed
        }}
      slack-announcing-id: spring-security-announcing
  test:
    name: Test Against Snapshots
    secrets: inherit
    strategy:
      matrix:
        include:
        - java-version: 21-ea
          toolchain: 21
        - java-version: 17
          toolchain: 17
    uses: spring-io/spring-security-release-tools/.github/workflows/test.yml@v1
    with:
      java-version: ${{ matrix.java-version }}
      test-args: --refresh-dependencies -PforceMavenRepositories=snapshot -PisOverrideVersionCatalog
        -PtestToolchain=${{ matrix.toolchain }} -PspringFrameworkVersion=6.2.+ -PreactorVersion=2023.0.+
        -PspringDataVersion=2024.0.+ --stacktrace
name: CI
on:
  repository_dispatch:
    types: trigger-ga___continuous-integration-workflow.yml
permissions:
  contents: read
