concurrency:
  group: dependabot-auto-merge-forward
jobs:
  auto-merge-forward-dependabot:
    name: Auto Merge Forward Dependabot Commits
    needs:
    - get-supported-branches
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: checkout
      name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
    - continue-on-error: true
      id: setup-gh-user
      name: Setup GitHub User
      run: 'git config user.name ''github-actions[bot]''

        git config user.email ''github-actions[bot]@users.noreply.github.com''

        '
    - continue-on-error: true
      id: run-auto-merge-forward
      name: Run Auto Merge Forward
      uses: spring-io/spring-security-release-tools/.github/actions/auto-merge-forward@actions-v1
      with:
        branches: ${{ needs.get-supported-branches.outputs.supported_versions }},main
        from-author: dependabot[bot]
  get-supported-branches:
    uses: spring-io/spring-security-release-tools/.github/workflows/retrieve-spring-supported-versions.yml@actions-v1
    with:
      project: spring-security
      repository_name: spring-projects/spring-security
      type: oss
  notify_result:
    if: failure()
    name: Check for failures
    needs:
    - auto-merge-forward-dependabot
    permissions:
      actions: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Send Slack message
      uses: Gamesight/slack-workflow-status@v1.3.0
      with:
        channel: '#spring-security-ci'
        name: CI Notifier
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
name: Auto Merge Forward Dependabot Commits
on:
  repository_dispatch:
    types: trigger-ga___dependabot-auto-merge-forward.yml
permissions:
  contents: read
