env:
  DUE_ON: ${{ github.event.milestone.due_on }}
  TITLE: ${{ github.event.milestone.title }}
jobs:
  notify_result:
    if: failure()
    name: Check for failures
    needs:
    - spring-releasetrain-checks
    permissions:
      actions: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Send Slack message
      uses: Gamesight/slack-workflow-status@v1.3.0
      with:
        channel: '#spring-security-ci'
        name: CI Notifier
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  spring-releasetrain-checks:
    if: ${{ github.repository == 'spring-projects/spring-security' }}
    name: Check DueOn is on a Release Date
    permissions:
      contents: none
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Print Milestone Being Checked
      run: echo "Validating DueOn '$DUE_ON' for milestone '$TITLE'"
    - continue-on-error: true
      if: env.DUE_ON != ''
      name: Validate DueOn
      run: 'export TOOL_VERSION=0.1.1

        wget "https://repo.maven.apache.org/maven2/io/spring/releasetrain/spring-release-train-tools/$TOOL_VERSION/spring-release-train-tools-$TOOL_VERSION.jar"

        java -cp "spring-release-train-tools-$TOOL_VERSION.jar" io.spring.releasetrain.CheckMilestoneDueOnMain
        --dueOn "$DUE_ON" --expectedDayOfWeek MONDAY --expectedMondayCount 3

        '
name: Check Milestone
on:
  repository_dispatch:
    types: trigger-ga___milestone-spring-releasetrain.yml
permissions:
  contents: read
