env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
jobs:
  build:
    if: ${{ github.repository == 'spring-projects/spring-security' }}
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up gradle
      uses: spring-io/spring-gradle-build-action@v2
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean build --continue
  generate-docs:
    if: ${{ github.repository == 'spring-projects/spring-security' }}
    name: Generate Docs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up gradle
      uses: spring-io/spring-gradle-build-action@v2
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Run Antora
      run: ./gradlew -PbuildSrc.skipTests=true :spring-security-docs:antora
    - continue-on-error: true
      id: upload
      name: Upload Docs
      uses: actions/upload-artifact@v4
      with:
        name: docs
        overwrite: true
        path: docs/build/site
name: PR Build
on:
  repository_dispatch:
    types: trigger-ga___pr-build-workflow.yml
permissions:
  contents: read
