jobs:
  dispatch_scheduled_releases:
    if: github.repository_owner == 'spring-projects'
    name: Dispatch scheduled releases
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      name: Dispatch
      run: gh workflow run update-scheduled-release-version.yml -r ${{ matrix.branch
        }}
    strategy:
      matrix:
        branch:
        - main
        - 6.3.x
        - 6.2.x
        - 5.8.x
name: Release Scheduler
on:
  repository_dispatch:
    types: trigger-ga___release-scheduler.yml
permissions: read-all
