jobs:
  update-antora-ui-spring:
    name: Update on Supported Branches
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Update
      uses: spring-io/spring-doc-actions/update-antora-spring-ui@5a57bcc6a0da2a1474136cf29571b277850432bc
      with:
        antora-file-path: docs/antora-playbook.yml
        docs-branch: ${{ matrix.branch }}
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        branch:
        - 5.8.x
        - 6.2.x
        - 6.3.x
        - main
  update-antora-ui-spring-docs-build:
    name: Update on docs-build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Update
      uses: spring-io/spring-doc-actions/update-antora-spring-ui@5a57bcc6a0da2a1474136cf29571b277850432bc
      with:
        docs-branch: docs-build
        token: ${{ secrets.GITHUB_TOKEN }}
name: Update Antora UI Spring
on:
  repository_dispatch:
    types: trigger-ga___update-antora-ui-spring.yml
permissions:
  contents: write
  issues: write
  pull-requests: write
