jobs:
  get-supported-branches:
    uses: spring-io/spring-security-release-tools/.github/workflows/retrieve-spring-supported-versions.yml@actions-v1
    with:
      project: spring-security
      repository_name: spring-projects/spring-security
      type: oss
  main:
    if: ${{ (github.repository == 'spring-projects/spring-security') && (github.ref
      == 'refs/heads/main') }}
    needs:
    - get-supported-branches
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - continue-on-error: true
      name: Update dependabot.yml
      uses: spring-io/spring-security-release-tools/.github/actions/generate-dependabot-yml@actions-v1
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        github-actions-branches: ${{ needs.get-supported-branches.outputs.supported_versions
          }},main,docs-build
        gradle-branches: ${{ needs.get-supported-branches.outputs.supported_versions
          }},main
    - continue-on-error: true
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update dependabot.yml
name: Update dependabot.yml
on:
  repository_dispatch:
    types: trigger-ga___update-dependabot.yml
permissions:
  contents: read
